/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReviewCommentsRouteImport } from './routes/review-comments'
import { Route as ReportBuilderRouteImport } from './routes/report-builder'
import { Route as ManagerReviewQueueRouteImport } from './routes/manager-review-queue'
import { Route as ManagerReviewPackRouteImport } from './routes/manager-review-pack'
import { Route as IssueMatrixRouteImport } from './routes/issue-matrix'
import { Route as HumanReviewRouteImport } from './routes/human-review'
import { Route as EvidenceWorkspaceRouteImport } from './routes/evidence-workspace'
import { Route as ConclusionRouteImport } from './routes/conclusion'
import { Route as CaseSetupRouteImport } from './routes/case-setup'
import { Route as CaseOverviewRouteImport } from './routes/case-overview'
import { Route as AuditTrailRouteImport } from './routes/audit-trail'
import { Route as AskLlmRouteImport } from './routes/ask-llm'
import { Route as AllegationReviewRouteImport } from './routes/allegation-review'
import { Route as AllegationIntakeRouteImport } from './routes/allegation-intake'
import { Route as AllegationAssessmentRouteImport } from './routes/allegation-assessment'
import { Route as IndexRouteImport } from './routes/index'

const ReviewCommentsRoute = ReviewCommentsRouteImport.update({
  id: '/review-comments',
  path: '/review-comments',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportBuilderRoute = ReportBuilderRouteImport.update({
  id: '/report-builder',
  path: '/report-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerReviewQueueRoute = ManagerReviewQueueRouteImport.update({
  id: '/manager-review-queue',
  path: '/manager-review-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerReviewPackRoute = ManagerReviewPackRouteImport.update({
  id: '/manager-review-pack',
  path: '/manager-review-pack',
  getParentRoute: () => rootRouteImport,
} as any)
const IssueMatrixRoute = IssueMatrixRouteImport.update({
  id: '/issue-matrix',
  path: '/issue-matrix',
  getParentRoute: () => rootRouteImport,
} as any)
const HumanReviewRoute = HumanReviewRouteImport.update({
  id: '/human-review',
  path: '/human-review',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceWorkspaceRoute = EvidenceWorkspaceRouteImport.update({
  id: '/evidence-workspace',
  path: '/evidence-workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const ConclusionRoute = ConclusionRouteImport.update({
  id: '/conclusion',
  path: '/conclusion',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseSetupRoute = CaseSetupRouteImport.update({
  id: '/case-setup',
  path: '/case-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseOverviewRoute = CaseOverviewRouteImport.update({
  id: '/case-overview',
  path: '/case-overview',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditTrailRoute = AuditTrailRouteImport.update({
  id: '/audit-trail',
  path: '/audit-trail',
  getParentRoute: () => rootRouteImport,
} as any)
const AskLlmRoute = AskLlmRouteImport.update({
  id: '/ask-llm',
  path: '/ask-llm',
  getParentRoute: () => rootRouteImport,
} as any)
const AllegationReviewRoute = AllegationReviewRouteImport.update({
  id: '/allegation-review',
  path: '/allegation-review',
  getParentRoute: () => rootRouteImport,
} as any)
const AllegationIntakeRoute = AllegationIntakeRouteImport.update({
  id: '/allegation-intake',
  path: '/allegation-intake',
  getParentRoute: () => rootRouteImport,
} as any)
const AllegationAssessmentRoute = AllegationAssessmentRouteImport.update({
  id: '/allegation-assessment',
  path: '/allegation-assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/allegation-assessment': typeof AllegationAssessmentRoute
  '/allegation-intake': typeof AllegationIntakeRoute
  '/allegation-review': typeof AllegationReviewRoute
  '/ask-llm': typeof AskLlmRoute
  '/audit-trail': typeof AuditTrailRoute
  '/case-overview': typeof CaseOverviewRoute
  '/case-setup': typeof CaseSetupRoute
  '/conclusion': typeof ConclusionRoute
  '/evidence-workspace': typeof EvidenceWorkspaceRoute
  '/human-review': typeof HumanReviewRoute
  '/issue-matrix': typeof IssueMatrixRoute
  '/manager-review-pack': typeof ManagerReviewPackRoute
  '/manager-review-queue': typeof ManagerReviewQueueRoute
  '/report-builder': typeof ReportBuilderRoute
  '/review-comments': typeof ReviewCommentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/allegation-assessment': typeof AllegationAssessmentRoute
  '/allegation-intake': typeof AllegationIntakeRoute
  '/allegation-review': typeof AllegationReviewRoute
  '/ask-llm': typeof AskLlmRoute
  '/audit-trail': typeof AuditTrailRoute
  '/case-overview': typeof CaseOverviewRoute
  '/case-setup': typeof CaseSetupRoute
  '/conclusion': typeof ConclusionRoute
  '/evidence-workspace': typeof EvidenceWorkspaceRoute
  '/human-review': typeof HumanReviewRoute
  '/issue-matrix': typeof IssueMatrixRoute
  '/manager-review-pack': typeof ManagerReviewPackRoute
  '/manager-review-queue': typeof ManagerReviewQueueRoute
  '/report-builder': typeof ReportBuilderRoute
  '/review-comments': typeof ReviewCommentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/allegation-assessment': typeof AllegationAssessmentRoute
  '/allegation-intake': typeof AllegationIntakeRoute
  '/allegation-review': typeof AllegationReviewRoute
  '/ask-llm': typeof AskLlmRoute
  '/audit-trail': typeof AuditTrailRoute
  '/case-overview': typeof CaseOverviewRoute
  '/case-setup': typeof CaseSetupRoute
  '/conclusion': typeof ConclusionRoute
  '/evidence-workspace': typeof EvidenceWorkspaceRoute
  '/human-review': typeof HumanReviewRoute
  '/issue-matrix': typeof IssueMatrixRoute
  '/manager-review-pack': typeof ManagerReviewPackRoute
  '/manager-review-queue': typeof ManagerReviewQueueRoute
  '/report-builder': typeof ReportBuilderRoute
  '/review-comments': typeof ReviewCommentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/allegation-assessment'
    | '/allegation-intake'
    | '/allegation-review'
    | '/ask-llm'
    | '/audit-trail'
    | '/case-overview'
    | '/case-setup'
    | '/conclusion'
    | '/evidence-workspace'
    | '/human-review'
    | '/issue-matrix'
    | '/manager-review-pack'
    | '/manager-review-queue'
    | '/report-builder'
    | '/review-comments'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/allegation-assessment'
    | '/allegation-intake'
    | '/allegation-review'
    | '/ask-llm'
    | '/audit-trail'
    | '/case-overview'
    | '/case-setup'
    | '/conclusion'
    | '/evidence-workspace'
    | '/human-review'
    | '/issue-matrix'
    | '/manager-review-pack'
    | '/manager-review-queue'
    | '/report-builder'
    | '/review-comments'
  id:
    | '__root__'
    | '/'
    | '/allegation-assessment'
    | '/allegation-intake'
    | '/allegation-review'
    | '/ask-llm'
    | '/audit-trail'
    | '/case-overview'
    | '/case-setup'
    | '/conclusion'
    | '/evidence-workspace'
    | '/human-review'
    | '/issue-matrix'
    | '/manager-review-pack'
    | '/manager-review-queue'
    | '/report-builder'
    | '/review-comments'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AllegationAssessmentRoute: typeof AllegationAssessmentRoute
  AllegationIntakeRoute: typeof AllegationIntakeRoute
  AllegationReviewRoute: typeof AllegationReviewRoute
  AskLlmRoute: typeof AskLlmRoute
  AuditTrailRoute: typeof AuditTrailRoute
  CaseOverviewRoute: typeof CaseOverviewRoute
  CaseSetupRoute: typeof CaseSetupRoute
  ConclusionRoute: typeof ConclusionRoute
  EvidenceWorkspaceRoute: typeof EvidenceWorkspaceRoute
  HumanReviewRoute: typeof HumanReviewRoute
  IssueMatrixRoute: typeof IssueMatrixRoute
  ManagerReviewPackRoute: typeof ManagerReviewPackRoute
  ManagerReviewQueueRoute: typeof ManagerReviewQueueRoute
  ReportBuilderRoute: typeof ReportBuilderRoute
  ReviewCommentsRoute: typeof ReviewCommentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/review-comments': {
      id: '/review-comments'
      path: '/review-comments'
      fullPath: '/review-comments'
      preLoaderRoute: typeof ReviewCommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-builder': {
      id: '/report-builder'
      path: '/report-builder'
      fullPath: '/report-builder'
      preLoaderRoute: typeof ReportBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager-review-queue': {
      id: '/manager-review-queue'
      path: '/manager-review-queue'
      fullPath: '/manager-review-queue'
      preLoaderRoute: typeof ManagerReviewQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager-review-pack': {
      id: '/manager-review-pack'
      path: '/manager-review-pack'
      fullPath: '/manager-review-pack'
      preLoaderRoute: typeof ManagerReviewPackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issue-matrix': {
      id: '/issue-matrix'
      path: '/issue-matrix'
      fullPath: '/issue-matrix'
      preLoaderRoute: typeof IssueMatrixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/human-review': {
      id: '/human-review'
      path: '/human-review'
      fullPath: '/human-review'
      preLoaderRoute: typeof HumanReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence-workspace': {
      id: '/evidence-workspace'
      path: '/evidence-workspace'
      fullPath: '/evidence-workspace'
      preLoaderRoute: typeof EvidenceWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conclusion': {
      id: '/conclusion'
      path: '/conclusion'
      fullPath: '/conclusion'
      preLoaderRoute: typeof ConclusionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-setup': {
      id: '/case-setup'
      path: '/case-setup'
      fullPath: '/case-setup'
      preLoaderRoute: typeof CaseSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-overview': {
      id: '/case-overview'
      path: '/case-overview'
      fullPath: '/case-overview'
      preLoaderRoute: typeof CaseOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-trail': {
      id: '/audit-trail'
      path: '/audit-trail'
      fullPath: '/audit-trail'
      preLoaderRoute: typeof AuditTrailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask-llm': {
      id: '/ask-llm'
      path: '/ask-llm'
      fullPath: '/ask-llm'
      preLoaderRoute: typeof AskLlmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/allegation-review': {
      id: '/allegation-review'
      path: '/allegation-review'
      fullPath: '/allegation-review'
      preLoaderRoute: typeof AllegationReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/allegation-intake': {
      id: '/allegation-intake'
      path: '/allegation-intake'
      fullPath: '/allegation-intake'
      preLoaderRoute: typeof AllegationIntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/allegation-assessment': {
      id: '/allegation-assessment'
      path: '/allegation-assessment'
      fullPath: '/allegation-assessment'
      preLoaderRoute: typeof AllegationAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AllegationAssessmentRoute: AllegationAssessmentRoute,
  AllegationIntakeRoute: AllegationIntakeRoute,
  AllegationReviewRoute: AllegationReviewRoute,
  AskLlmRoute: AskLlmRoute,
  AuditTrailRoute: AuditTrailRoute,
  CaseOverviewRoute: CaseOverviewRoute,
  CaseSetupRoute: CaseSetupRoute,
  ConclusionRoute: ConclusionRoute,
  EvidenceWorkspaceRoute: EvidenceWorkspaceRoute,
  HumanReviewRoute: HumanReviewRoute,
  IssueMatrixRoute: IssueMatrixRoute,
  ManagerReviewPackRoute: ManagerReviewPackRoute,
  ManagerReviewQueueRoute: ManagerReviewQueueRoute,
  ReportBuilderRoute: ReportBuilderRoute,
  ReviewCommentsRoute: ReviewCommentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
